## Unsupervised Concept Based Explanantions (Initial Commit, Testing in Progress...)

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from src.transformer_models import Bert,DistilGPT2, DistilBert
from transformers import AutoTokenizer
from datasets import load_dataset, concatenate_datasets, DatasetDict, Dataset

In [20]:
from train_models import get_dataset

## Setup dataset

In [60]:
# read data
from src.dataset import load_gtc
data_use = "Counseling"
genocide_ds = get_dataset(data_use) #load_gtc("Dataset_GTC-V2.csv")

In [61]:
def preprocess_function(examples):
    """Preprocess function for the dataset"""
    return btm.tokenizer(examples['text'], padding='max_length', truncation=True, max_length=512)

In [62]:
from src.classification_models import RoBERTaPretrainedmodel

In [63]:
btm = RoBERTaPretrainedmodel(device="cuda:2")

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at FacebookAI/roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [81]:
btm.tokenizer

RobertaTokenizerFast(name_or_path='FacebookAI/roberta-base', vocab_size=50265, model_max_length=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<s>', 'eos_token': '</s>', 'unk_token': '<unk>', 'sep_token': '</s>', 'pad_token': '<pad>', 'cls_token': '<s>', 'mask_token': '<mask>'}, clean_up_tokenization_spaces=True),  added_tokens_decoder={
	0: AddedToken("<s>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
	1: AddedToken("<pad>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
	2: AddedToken("</s>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
	3: AddedToken("<unk>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
	50264: AddedToken("<mask>", rstrip=False, lstrip=True, single_word=False, normalized=False, special=True),
}

In [84]:
btm.tokenizer("Hello!", padding="max_length")

{'input_ids': [0, 31414, 328, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [64]:
#btm.load("logs_GTC/models/RoBERTaPretrainedmodel_n_layers-12_lr-2.043706578410144e-06.pt")
#btm.load("logs_PTSD/models/RoBERTaPretrainedmodel_n_layers-7_lr-6.433852622590321e-06_PTSD_r0.pt")
btm.load("logs_Counseling/models/RoBERTaPretrainedmodel_n_layers-4_lr-9.54840074956384e-05_Counseling_r0.pt")

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at FacebookAI/roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [65]:
genocide_ds.set_format("torch")
ds_tokenized = genocide_ds.map(preprocess_function, batched=True)

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

Map:   0%|          | 0/200 [00:00<?, ? examples/s]

## Load a trained model to discover concepts

In [66]:
import torch
dataloader_train = torch.utils.data.DataLoader(ds_tokenized['train'], batch_size=12, shuffle=True)
dataloader_test = torch.utils.data.DataLoader(ds_tokenized['test'], batch_size=12, shuffle=False)

In [67]:
from src.concept_explanations import ConceptSHAP

The main parameter of choice for the concept explanations are ``n_concepts``, the number of concepts (clusters) that should be discovered, ``snippet_len`` the number of tokens that should be used as the length of the instances in one cluster. A lower length makes the clusters more coherent, but is also less nuances (mostly words that reappear). Longer lengths can be seemingly less meaningful, but can have a higher level of abstraction...

In [68]:
cshap = ConceptSHAP(btm, n_concepts=10, num_classes=2, force_orth = True, snippet_len = 5)

In [69]:
## Fit the concepts to the clursting
cshap.discover_concepts(dataloader_train, device="cuda:2", n_epochs=5)

Epoch 0
Epoch: [0][ 0/84]	Time  0.178 ( 0.178)	Data  0.004 ( 0.004)	Loss -8.6176e-02 (-8.6176e-02)	Acc@1 100.00 (100.00)
Epoch: [0][20/84]	Time  0.125 ( 0.126)	Data  0.009 ( 0.004)	Loss -7.2735e-01 (-5.7743e-01)	Acc@1  91.67 ( 94.05)
Epoch: [0][40/84]	Time  0.137 ( 0.124)	Data  0.004 ( 0.004)	Loss -1.2726e+00 (-7.4882e-01)	Acc@1 100.00 ( 92.89)
Epoch: [0][60/84]	Time  0.129 ( 0.124)	Data  0.006 ( 0.004)	Loss -1.7701e+00 (-9.3611e-01)	Acc@1 100.00 ( 92.35)
Epoch: [0][80/84]	Time  0.123 ( 0.123)	Data  0.008 ( 0.004)	Loss -2.0978e+00 (-1.1209e+00)	Acc@1 100.00 ( 91.77)
Epoch 1
Epoch: [1][ 0/84]	Time  0.122 ( 0.122)	Data  0.003 ( 0.003)	Loss -2.2140e+00 (-2.2140e+00)	Acc@1 100.00 (100.00)
Epoch: [1][20/84]	Time  0.095 ( 0.123)	Data  0.003 ( 0.005)	Loss -2.1459e+00 (-2.1334e+00)	Acc@1  91.67 ( 94.05)
Epoch: [1][40/84]	Time  0.096 ( 0.122)	Data  0.003 ( 0.005)	Loss -2.3594e+00 (-2.1927e+00)	Acc@1  91.67 ( 91.87)
Epoch: [1][60/84]	Time  0.133 ( 0.123)	Data  0.003 ( 0.005)	Loss -2.7825e+00 (-2

In [70]:
cbert = cshap.cresnet.to("cpu")

In [71]:
torch.save(cbert, f"logs/explanations/concept_shap_cls_{data_use}_10_5.pt")

In [72]:
import torch
cbert = torch.load(f"logs/explanations/concept_shap_cls_{data_use}_10_5.pt")

## Now analyze the clusters.

The find_concepts_runs the entire dataset through the concept model to return the closest samples to the discovered concepts.

In [73]:
from src.concept_explanations import find_concepts

In [74]:
dataloader_test = torch.utils.data.DataLoader(ds_tokenized['train'], batch_size=2, shuffle=False)

This function returns the dot products (concept alignments, classes, sample ids, and the tokens) for the $N$ best matches in the dataset for one of the discovered concepts.

In [75]:
closest_dots, closest_class, closest_imgids, closest_tokens = find_concepts(dataloader_test, cbert, N=25, device="cuda:2", len_tokens=5)

Batch:[  0/500]	Time  0.040 ( 0.040)	Data  0.007 ( 0.007)
Batch:[100/500]	Time  0.034 ( 0.033)	Data  0.003 ( 0.006)
Batch:[200/500]	Time  0.043 ( 0.033)	Data  0.008 ( 0.006)
Batch:[300/500]	Time  0.022 ( 0.033)	Data  0.003 ( 0.006)
Batch:[400/500]	Time  0.029 ( 0.033)	Data  0.003 ( 0.006)


How much trauma in the top samples for each concept?

Which of the discovered concepts are trauma related?

In [76]:
closest_class.float().mean(dim=1) ## Find how many of the the examples for each concept are traumatic

tensor([0.1200, 0.0400, 0.0000, 0.0000, 0.3200, 0.3600, 0.3200, 0.2800, 0.0400,
        0.4400], device='cuda:2')

In [77]:
trauma_related = torch.where(closest_class.float().mean(dim=1) > 0.5)[0]

In [78]:
print(trauma_related)

tensor([], device='cuda:2', dtype=torch.int64)


Concept 1 = prison camps

Concept 2 = firearms

Concept 4 = torture

Concept 6 = dead bodies

Concept 8 = flee

In [79]:
for i in range(len(closest_tokens)):
    print("-- CONCEPT", i, "--")
    num_toks = 15
    for j in range(num_toks):
        print(btm.tokenizer.decode(closest_tokens[i,j].cpu()) + (r"\\" if j != num_toks-1 else ""))

-- CONCEPT 0 --
My boyfriend lost his dad\\
 shot and killed my rapist\\
 my mom. My dad\\
 his wife. My uncle\\
 His mom, my grandma\\
<s><s><s><s><s>\\
<s><s><s><s><s>\\
<s><s><s><s><s>\\
<s><s><s><s><s>\\
<s><s><s><s><s>\\
<s><s><s><s><s>\\
<s><s><s><s><s>\\
<s><s><s><s><s>\\
<s><s><s><s><s>\\
<s><s><s><s><s>
-- CONCEPT 1 --
 My boyfriend and I hit\\
 university was my savior.\\
ogue about how to discuss\\
 ask more questions about what\\
I was raped a couple\\
 Some relaxation and meditation exercises\\
 to decide what to do\\
 have to do to prepare\\
 you will need to encourage\\
 may choose not to discuss\\
 ask questions to focus on\\
 If you want to discuss\\
 how to feel about it\\
 sure what to feel to\\
 may want to consider seeing
-- CONCEPT 2 --
<s><s><s><s><s>\\
<s><s><s><s><s>\\
<s><s><s><s><s>\\
<s><s><s><s><s>\\
<s><s><s><s><s>\\
<s><s><s><s><s>\\
<s><s><s><s><s>\\
<s><s><s><s><s>\\
<s><s><s><s><s>\\
<s><s><s><s><s>\\
<s><s><s><s><s>\\
<s><s><s><s><s>\\
<s><s><s><s><s>

## Remarks

Concept 0: Killings execution

Concept 1: Shocking, receiving news of traumatic events.

Concept 2: Did that think, general court speech

Concept 3: Injuries

Concept 4: Living conditions, indicrect trauma of war

In [164]:
def print_most_common_tokens(input_array, n=10):
    values, counts = torch.unique(input_array.flatten(), return_counts=True)
    indices = torch.argsort(counts, descending=True)
    for i in values[indices[:n]]:
        if i not in [0, 101, 102]:
            str = tokenizer.convert_ids_to_tokens(i.item())
            if str not in ["the", "a", "of", "was", ",", "i", "he", "in", ".", "to", "and", "-", "'", "-", "that", "?", "were", "my", "had", "they"]:
                print(str)
    print(values[indices[:n]])

In [166]:
print_most_common_tokens(closest_tokens[2], 100)

Ġthe
Ġwere
ĠI
</s>
Ġand
Ġa
Ġin
Ġwith
Ġwas
Ġor
Ġwe
Ġme
Ġhead
Ġhit
Ġshot
Ġkilled
Ġthemselves
Ġwounded
Ġbullet
Ġgunshots
Ġto
Ġof
Ġfor
Ġthat
Ġon
Ġit
Ġbe
Ġby
Ġfrom
Ġthey
Ġone
Ġso
I
Ġsome
Ġcould
Ġmy
Ġthree
;
Ġthose
Ġwork
Ġeven
Ġset
Ġgot
Ġevery
Ġnight
Ġfeel
Ġfire
Ġonce
Ġfood
Ġsaw
Ġbody
Ġreceived
Ġanything
Ġrest
Ġvarious
Ġdead
Ġkept
Ġsupply
Ġhear
Ġmyself
Ġfear
Ġlived
Ġanimals
Ġwedding
Ġbodies
Ġdry
Ġconstant
Ġeverywhere
Ġburned
Ġwound
Ġcry
Ġcrying
Ġbullets
Ġgunfire
Ġcows
chy
Ġshells
hoe
Ġbursts
Ġdiarr
tensor([    4,     5,    58,    38,     2,     6,     8,    10,    11,    19,
           21,    50,    52,   162,   471,   478,   738,   848,  1235,  5424,
         8894, 21715,     7,     9,    13,    14,    15,    24,    28,    30,
           31,    51,    65,    98,   100,   102,   103,   115,   127,   130,
          131,   167,   173,   190,   278,   300,   358,   363,   619,   668,
          683,   689,   794,   809,   829,   932,  1079,  1337,  1462,  1682,
         1787,  1798,  2185,  2490

In [204]:
## Retrieve examples

from collections import defaultdict
def get_examples(example_ids, dataloader_train):
    my_dict = defaultdict(int)
    bs = dataloader_train.batch_size
    for i, data in enumerate(dataloader_train):
        mytexts = data["texts"]
        for ids in example_ids:
            if i*batch_size <= ids and ids < (i+1)*batch_size:
                my_dict[ids] = texts[ids-i*batch_size]
    return my_dict

In [62]:
torch.save(model_trained, "genocide_bert.pt")

## Find a test sample to explain with SLALOM

In [67]:
dataloader_test = torch.utils.data.DataLoader(trainer.ds_tokenized['test'], batch_size=32, shuffle=False)
model_trained = model_trained.eval()
batch = next(iter(dataloader_test))
input_ids = batch['input_ids'].to(device)
attention_mask = batch['attention_mask'].to(device)
labels = batch['label'].to(device)
outputs = model_trained(input_ids, attention_mask=attention_mask, labels=labels)
predictions = torch.argmax(outputs['logits'], dim=-1).cpu()
print(predictions)

tensor([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 1, 0, 0, 0, 1, 0, 0])
